### ISSUE TITLE
Reload time scaling is extreme

### ISSUE THREAD

**Issue by DarioXN** [Muushy/Sprocket-Feedback#525] opened 2024-04-05 16:56 UTC
Title, the reload times for small guns are more or less fine, but for bigger guns (ex 105x620mm), it can be 90 seconds or more.
Another issue is that going over about 130 seconds leads to the gun never loading, only being able to fire one shot.

**Comment by Muushy** [comment] 2024-04-08 14:35
Dupe of #442

**Closed as not planned by Muushy** 2024-04-08 14:35 UTC
Labels: bug
