### ISSUE TITLE
Armor Holes Between Faces

### ISSUE THREAD

**Issue by Cui-Qui** [Muushy/Sprocket-Feedback#723] opened 2024-12-23 05:24 UTC
When you have a high smooth angle (in my case 45) and have two faces on a high positive angle

0.2.24.7

Set your smooth angle to a high amount, and have a face in a high positive angle.

Note: It can be fixed by either lowering the slope angle or by lowering the face's angle.

![Armor holes 1](https://github.com/user-attachments/assets/a1880dbb-14e9-488b-a984-fc7c1f488c5d)
![Armor holes 2](https://github.com/user-attachments/assets/ce47e321-4716-4875-acac-9a7f6ecf1fe9)

**Comment by Muushy** [comment] 2024-12-30 11:53
Dupe of #472

**Closed as not planned by Muushy** 2024-12-30 11:53 UTC
Labels: bug
