### ISSUE TITLE
Opening prompt while another prompt is open causes a non-functional placeholder prompt to appear.

### ISSUE THREAD

**Issue by DarioXN** [Muushy/Sprocket-Feedback#111] opened 2022-08-07 06:40 UTC
Requires restart to fix.

**Comment by Muushy** [comment] 2022-08-11 13:53
Can't reproduce.

**Comment by Muushy** [comment] 2022-08-11 16:20
Reset button was broken.

**Comment by Muushy** [comment] 2022-08-18 10:15
Fixed in V0.123

**Closed as completed by Muushy** 2022-08-18 10:15 UTC
Labels: bug
