### ISSUE TITLE
Engine and transmission are selectable through hull and add their menu stuff to the right side of the screen

### ISSUE THREAD

**Issue by CSNelson7** [Muushy/Sprocket-Feedback#617] opened 2024-08-30 00:10 UTC
![image_2024-08-29_160932608](https://github.com/user-attachments/assets/366f99c5-b60a-49ee-8f01-45f976b52c1f)

As described in the title. This is rather annoying when attempting to work on tracks because i keep accidently selecting the engine or transmission and having them interrupt my work.

**Comment by Muushy** [comment] 2024-09-02 16:34
Dupe of #572

**Closed as not planned by Muushy** 2024-09-02 16:34 UTC
Labels: bug
