### ISSUE TITLE
Collisions on sandbox map

### ISSUE THREAD

**Issue by DarioXN** [Muushy/Sprocket-Feedback#207] opened 2022-11-01 21:15 UTC
The collision meshes on the sandbox map do not line up with the actual map itself (mostly around the rocks).

![image](https://user-images.githubusercontent.com/109303520/199342216-c64930eb-4587-413c-9c93-01a2abcc8548.png)

(can't go any farther forwards)
![image](https://user-images.githubusercontent.com/109303520/199342411-06bdf186-f527-46d5-9f1f-9b230b84229e.png)

![image](https://user-images.githubusercontent.com/109303520/199342734-7a18680b-5b92-40a8-98c6-8882a60621db.png)

**Comment by Muushy** [comment] 2022-11-03 15:29
Dupe of #7

**Closed as not planned by Muushy** 2022-11-03 15:29 UTC
Labels: bug
