### ISSUE TITLE
Track behavior is significantly affected by physics settings

### ISSUE THREAD

**Issue by SprocketTools** [Muushy/Sprocket-Feedback#470] opened 2024-03-31 07:51 UTC
Low:
![image](https://github.com/Muushy/Sprocket-Feedback/assets/137387488/47a4d42c-2912-4d03-8602-e61d8a507d71)

Medium:
![image](https://github.com/Muushy/Sprocket-Feedback/assets/137387488/80791107-d570-4063-bb06-d77aa58597ce)

High:
![image](https://github.com/Muushy/Sprocket-Feedback/assets/137387488/be94d746-9f96-4821-8fee-f3e53d33bc77)

**Game version:**
V0.2 B0

**Comment by DarioXN** [comment] 2024-03-31 07:55
Dupe of #302

**Comment by Muushy** [comment] 2024-04-02 16:16
Keeping open as the suggestion in #302 has some potential which should be looked at, and this post has good images.

**Comment by Muushy** [comment] 2024-10-29 14:11
Physics settings removed in 0.2.20

**Closed as completed by Muushy** 2024-10-29 14:11 UTC
Labels: bug, duplicate
