### ISSUE TITLE
Reassigning keybinds does not work in 0.2 Alpha

### ISSUE THREAD

**Issue by robotnikthingy** [Muushy/Sprocket-Feedback#619] opened 2024-09-01 04:37 UTC
**Describe the bug**
Reassigning keybinds does not work. It will show in the settings as changed, but in game they still use the default ones.

**Version**
0.2 Alpha

**To Reproduce**
-reassign any keybind to something else
-try using new keybind

**Expected behavior**
controls should be reassigned to the new key

**Screenshots**

**Additional context**

**Comment by Muushy** [comment] 2024-09-02 16:33
Dupe of #459

**Closed as not planned by Muushy** 2024-09-02 16:33 UTC
Labels: bug
