### ISSUE TITLE
Shadows are not aligned properly on some objects

### ISSUE THREAD

**Issue by SprocketTools** [Muushy/Sprocket-Feedback#471] opened 2024-03-31 08:15 UTC
**Describe the bug**
https://github.com/Muushy/Sprocket-Feedback/assets/137387488/84ce41d8-1a7a-4f28-9ee2-d358840601d9

**Version**
V0.2 B0

**Comment by Muushy** [comment] 2024-04-02 16:45
Dupe of #440

**Closed as not planned by Muushy** 2024-04-02 16:45 UTC
Labels: bug
