### ISSUE TITLE
Roadwheels glitching out.

### ISSUE THREAD

**Issue by Harbisonel** [Muushy/Sprocket-Feedback#724] opened 2024-12-24 17:44 UTC
**Describe the bug**
Roadwheels change position while turning.

**Version**
Newest 0.2 beta - after Fields re-introduction.

**To Reproduce**
1. Create a tank, best on flat sandbox map for easier observation. The error will appear with clutch braking, didn't check twin transmission.
2. Try turning on the spot, with one track not moving.
3. Observe the roadwheels on the not-moving innter track.

**Expected behavior**
Roadwheels should stay in position.

**Screenshots**
Screenshot of the tank when turning, notice the first and last wheels especially.
![20241223162047_1](https://github.com/user-attachments/assets/3ce71b70-05a4-45e0-af2f-8bb9dacccea7)
Screenshot taken after tapping "W": (How the tank should look like):
![20241223162050_1](https://github.com/user-attachments/assets/17bac636-d55b-4110-aba8-366f82e7d053)

**Comment by Muushy** [comment] 2024-12-30 11:51
Dupe of #269

**Closed as not planned by Muushy** 2024-12-30 11:51 UTC
Labels: bug
