### ISSUE TITLE
Track getting bug when sized too small

### ISSUE THREAD

**Issue by Geekman18** [Muushy/Sprocket-Feedback#590] opened 2024-07-24 20:39 UTC
When i unsync the tracks to chassis and go under 5100mm in size. The tracks get visually stuck at that size and can't be resize 

Version 0.2.9

1. Go on the track menu
2. Click on sync to chassis
3. Scroll under 5100mm on length
4. And the track refuse to go smaller or bigger
5. Need to create a new to tank to fix the issue
6. And make unable to do anything on the game if you try to play with a bugged vehicule

Screenshots:
![20240724223658_1](https://github.com/user-attachments/assets/5ed76eaa-c4b4-44d2-87b3-39edaec72ddc)
![20240724223647_1](https://github.com/user-attachments/assets/ed180a31-2aad-47d1-9112-6fe9aa42b87f)

**Comment by Muushy** [comment] 2024-07-29 10:47
This one was caused by the part loading issue introduced in 0.2.8.
It's fixed in 0.2.10.

**Closed as completed by Muushy** 2024-07-29 10:47 UTC
Labels: bug
