### ISSUE TITLE
Mirroring on transmissions does not properly move everything in one direction

### ISSUE THREAD

**Issue by SprocketTools** [Muushy/Sprocket-Feedback#437] opened 2024-03-30 18:13 UTC
**Describe the bug**
Transmission mirroring does not work properly.

**Version**
0.2 B0

https://github.com/Muushy/Sprocket-Feedback/assets/137387488/ba7d0ff3-fcdf-4d17-9373-c017e5a59270

**Comment by DarioXN** [comment] 2024-03-30 21:25
This happens when mirroring is turned off

**Comment by Muushy** [comment] 2024-04-03 14:28
Dupe of #445

**Closed as not planned by Muushy** 2024-04-03 14:28 UTC
Labels: bug
